app:
  build: .
  command: sh docker/start.sh
  volumes:
    - .:/usr/src/app
    - ./config/database.yml.default:/usr/src/app/config/database.yml
    - ./bundle:/usr/local/bundle
    - ./public:/usr/share/nginx/html/logdatablog

    - /home/david/uploads/logdatablog:/usr/src/app/public/uploads
    - tmp:/usr/src/app/tmp
    - "/var/run/postgresql:/var/run/postgresql"
    - "../../dumps:/usr/src/app/dumps"
  env_file:
    - database.env
    - api_secret.env
  environment:
    RAILS_ENV: "${RAILS_ENV}"
  restart: always
nginx:
  image: nginx
  links:
    - app
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./public:/usr/share/nginx/html/logdatablog

    - /home/david/uploads/logdatablog:/usr/share/nginx/html/logdatablog/uploads
    - "/share/logs/logdatablog_${RAILS_ENV}:/usr/src/app/log"
    - /home/david/ssl_certificates/logdatablog:/usr/share/nginx/html/ssl_certificates/logdatablog
  ports:
    - "3000:3000"
  expose:
    - "3000"
  restart: always
