app:
  build: .
  command: sh docker/start.sh
  volumes:
    - .:/usr/src/app
    - ./config/database.yml.default:/usr/src/app/config/database.yml
    - ./bundle:/usr/local/bundle
    - ./public:/usr/share/nginx/html
    - ./public/uploads:/usr/share/nginx/html/uploads
    - tmp:/usr/src/app/tmp
    - "/var/run/postgresql:/var/run/postgresql"
  env_file:
    - database.env
  environment:
    RAILS_ENV: "${RAILS_ENV}"
  restart: always
  expose:
    - "3000"
nginx:
  image: nginx
  links:
    - app
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./public:/usr/share/nginx/html
    - ./public/uploads:/usr/share/nginx/html/uploads
    - "/share/logs/logdatablog_${RAILS_ENV}:/usr/src/app/log"
  ports:
    - "3000:80"
    - "80:80"
  expose:
    - "80"
  restart: always
