app:
  build: .
  command: sh docker/start.sh
  volumes:
    - .:/usr/src/app
    - ./config/database.yml.default:/usr/src/app/config/database.yml
    - ./bundle:/usr/local/bundle
    - ./public:/usr/share/nginx/html/logdatablog

    - /home/david/uploads/logdatablog:/usr/src/app/public/uploads
    - tmp:/usr/src/app/tmp
    - "/var/run/postgresql:/var/run/postgresql"
    - "../../dumps:/usr/src/app/dumps"
    - "../../logs:/usr/src/app/log"
  env_file:
    - database.env
    - api_secret.env
  environment:
    RAILS_ENV: "${RAILS_ENV}"
    REDIS_URL: redis://redis:6379/
  restart: always
  links:
    - redis
nginx:
  image: nginx
  links:
    - app
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./public:/usr/share/nginx/html/logdatablog

    - /home/david/uploads/logdatablog:/usr/share/nginx/html/logdatablog/uploads
    - "../../logs:/var/log"
    - /home/david/ssl_certificates/logdatablog:/usr/share/nginx/html/ssl_certificates/logdatablog
  ports:
    - "3000:3000"
  expose:
    - "3000"
  restart: always

sidekiq:
  links:
    - redis
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml -L log/sidekiq.log
  volumes:
    - .:/usr/src/app
    - ./config/database.yml.default:/usr/src/app/config/database.yml
    - bundle:/usr/local/bundle
  env_file:
    - database.env
  environment:
    RAILS_ENV: "${RAILS_ENV}"
    REDIS_URL: redis://redis:6379/
    RAILS_RELATIVE_URL_ROOT: /hotel

redis:
  image: redis
  volumes:
    - redis_data:/data
  expose:
    - "6379"
