app:
  build: .
  command: sh docker/start.sh
  volumes:
    - .:/usr/src/app
    - ./config/database.yml.default:/usr/src/app/config/database.yml
    - ./bundle:/usr/local/bundle
    - ./public:/usr/share/nginx/html

    - /home/david/uploads:/usr/src/app/public/uploads
    - tmp:/usr/src/app/tmp
    - "/var/run/postgresql:/var/run/postgresql"
  env_file:
    - database.env
    - api_secret.env
  environment:
    RAILS_ENV: "${RAILS_ENV}"
  restart: always
  expose:
    - "3000"
nginx:
  image: nginx
  links:
    - app
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./public:/usr/share/nginx/html

    - /home/david/uploads:/usr/share/nginx/html/uploads
    - "/share/logs/logdatablog_${RAILS_ENV}:/usr/src/app/log"
    - /home/david/ssl_sercificate:/usr/share/nginx/html/ssl_sercificate
  ports:
    - "3000:443"
    - "443:443"
  expose:
    - "443"
  restart: always
