default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: '123'
  username: david

development:
  <<: *default
  database: logdatablog_development

test:
  <<: *default
  database: logdatablog_test

production:
  <<: *default
  database: logdatablog_production
  username: logdatablog
  password: <%= ENV['LOGDATABLOG_DATABASE_PASSWORD'] %>
